function comb = addDataComb(comb, data)
%%Extract processed photometry data from single data structure into a 
%%combined structure for ease of futher further analysis
%
% comb = addDataComb(comb, data);
%
% Description: Extract processed data from multiple recording 
% files into a larger structure to be used for further analysis
%
% INPUTS
%   'data' - Structure generated by processData scripts with recording from
%               a single recording
%
% OUPUTS
%   'comb' - Structure with data from multiple recordings
%
% Anya Krok, May 2026

if ~isstruct(comb)
    error('comb is not a structure.')
elseif isstruct(comb) && ~isempty(fieldnames(comb))
    a = 1 + length(comb);
elseif isstruct(comb) && isempty(fieldnames(comb)) % var is a struct with no fields
    a = 1;
end

comb(a).mouse = data.mouse; % store the loaded data in the structure
comb(a).date  = data.date; % store the loaded data in the structure
try
    comb(a).rec   = data.ID; % recording ID
catch
    comb(a).rec   = [data.mouse,'-',data.date]; % recording ID
end
comb(a).Fs = data.gen.Fs;
if isfield(data.final,'FP')
    comb(a).FP = data.final.FP;
    comb(a).FPnames = data.final.FPnames;
    try
        comb(a).time = data.final.time;
    catch
        comb(a).time = makeTime(numel(comb(a).FP{1}),comb(a).Fs);
    end
    if isfield(data.final,'nbFP')
        comb(a).nbFP = data.final.nbFP; % demodulated, non-baselined signal
    end
end
if isfield(data,'beh')
    comb(a).beh = data.beh;
end
comb(a).gen = data.gen;